services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  springboot:
    build: .
    container_name: springboot-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      MAIL_USERNAME: "cleanicsarl24@gmail.com"
      MAIL_PASSWORD: "wsuj dawn qmdd qyfq"
      JWT_SECRET: "G5pRQXJg7GwOULOE2VODLI9q3baigC4UcW3DYKGX//g="
      GOOGLE_MAPS_API_KEY: "AIzaSyAijDeBFgsJUYLqS6Nn3EQfi56cPPMtN_Q"
    restart: always

volumes:
  mongo_data:
