spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/pointage_cleanic

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: ${JWT_SECRET}


google:
  maps:
    api:
      key: "AIzaSyAijDeBFgsJUYLqS6Nn3EQfi56cPPMtN_Q"

app:
  frontend:
    base-url: ${APP_FRONTEND_BASE_URL:https://pointic-cleanic.com}
  conges:
    jours-acquis-par-an: ${CONGES_JOURS_ACQUIS_PAR_AN:22}
